# Generated by Django 2.1.5 on 2019-11-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='This T-Shirt is a fashionable and comfortable addition to your wardrobe.', max_length=750),
            preserve_default=False,
        ),
    ]
