# Generated by Django 2.1.5 on 2019-11-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('c', 'Checked Out'), ('t', 'Timed Out'), ('d', 'Deleted')], default='p', max_length=2),
        ),
    ]
